### ISSUE TITLE
Ticket restores session on `git commit`

### ISSUE THREAD

**Issue by erikw** [superDross/ticket.vim#22]
I have git configured to neovim `0.7.2` as my editor

```console
$ git config user.editor
nvim
```

ticket.vim is configured with 
```viml
let g:auto_ticket = 1
```

When I'm in a git project for which I have done `:SaveSession` is earlier and the do a commit with git that starts neovim:

```bash
$ git commit
```

then ticket.vim will restore the saved session. However in this case no session loading should be done so that one can enter a git commit message.

**Comment by superDross** [comment]
Thanks for opening this issue. This fix should ensure that auto opening or saving session does not occur when committing or rebasing via git.

@erikw you are welcome to reopen this issue if the bug persists

**Comment by erikw** [comment]
The fix works great so far, many thanks!
