### ISSUE TITLE
save session by checkout in lazygit

### ISSUE THREAD

**Issue by timsofteng** [superDross/ticket.vim#4]
hey. I'm interested in this plugin. Is it posible to save session by checkout in third part programm like lazygit? Thanks

**Comment by superDross** [comment]
I have never used it before but from taking a quick look at the lazygit README it seems like it should work seeing as it is a TUI wrapper for git commands.

**Comment by timsofteng** [comment]
@superDross ok, thanks, i'll try it today. Can you please implement saving session without git as well? I mean if vim cannot find git in current project session will save and called by directory name.

**Comment by superDross** [comment]
I am not sure how useful that feature would be over simply directly using `:mksession` or using a more suitable plugin like https://github.com/xolox/vim-session.

Nevertheless, If you open a separate issue I guess I could take a look at implementing this.

**Comment by timsofteng** [comment]
I have tried your plugin but it works not what i expect. I want to change my session on the fly whtn I change git branch. But when I switch branch in lazygit when vim is open nothing happens. Is it possible to implement changing sessions on the fly? Maybe if there are some unsaved files in current session popup with switching options will be useful.  For example when user have unsaved files and trying to checkout branch popup will ask what to do like to make all swap or save all. Is it make sense?

**Comment by superDross** [comment]
Its in the docs https://github.com/superDross/ticket.vim#settings

Place this in your vimrc:
```
let g:auto_ticket = 1
```

it will automatically open the session when opening vim and automatically save the session when exiting vim.

**Comment by timsofteng** [comment]
I got it. But I mean abiity to save and load session on the fly without closing vim.

**Comment by superDross** [comment]
So changing branch _while_ vim is still open? 

The auto features assumes you will close down vim before branch checkout.

 I don't think this is something I want to implement anytime soon. However, you are welcome to open a new feature request with a detailed explanation of the desired behavior and I can take a look at implementing it some time in the distant future.
