### ISSUE TITLE
Support XDG Base Directory Specification for `.tickets/`

### ISSUE THREAD

**Issue by erikw** [superDross/ticket.vim#9]
First of all, thanks for providing this very useful vim plugin, it's just what I've been looking for!

# Background
Lately the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been gaining quite a steady [popularity](https://wiki.archlinux.org/title/XDG_Base_Directory#Support), even though it's been around for a long time already. The basic idea is to standardize where programs put their files e.g. all config files in a certain directory. The benefits for end users are many, including:

* No polluted $HOME/
* Can easily grep for only config files in `$XDG_CONFIG_HOME`
* Can decide where to store configurations in more complex setups (multi system setup e.g.)
* Easily wipe state by removing `$XDG_STATE_HOME` or even `$XDG_DATA_HOME`, but without destroying and configuration files.

The first point is maybe what most end users enjoy the most though.

# How
Specifically for this project, this should mean that the search for the `.tickets/` directory file should be done like:

1. **If** `$XDG_DATA_HOME` is *set*, look for `$XDG_DATA_HOME/tickets-vim/`
1. **elseIf** `$XDG_DATA_HOME` is *unset*, use the default value for the envvar which is `$HOME/.local/share`. Thus, the config file to look for is at `$HOME/.local/share/tickets-vim/`
1. **else** fall-back to current legacy `$HOME/.tickets/`

The first two steps to can be codifed in bash like:
 `${XDG_DATA_HOME:-$HOME/.local/share}/tickets-vim`

Edit.
Replace the wrong `$XDG_CONFIG_DATA` with `$XDG_DATA_HOME`

**Comment by superDross** [comment]
@erikw this has been merged. I have tested this locally but I would appreciate it if you could test this yourself to ensure it follows the specifications detailed above.
